version: "3.1"
services:

    postgres:
      image: postgres:11.1-alpine
      container_name: foosleague-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=foosleague
      ports:
        - "10003:5432"

    webserver:
      image: nginx:alpine
      container_name: foosleague-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9999:80"

    php-fpm:
      build: docker/php-fpm
      container_name: foosleague-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

