version: "3.1"
services:
    postgres:
      image: postgres:11-alpine
      container_name: foosleague-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=foosleague
      ports:
        - "10003:5432"
    php-apache:
      build: docker/php-apache
      container_name: foosleague-php
      working_dir: /var/www/html
      volumes:
      - .:/var/www/html
      - ./docker/php-apache/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      ports:
        - "9999:8080"
